version: "3.8"

services:
  django:
    build: ./django
    container_name: django-dev
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
      - ./staticfiles:/app/django
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - webnet

  nginx:
    build: ./nginx-1.26.3
    container_name: nginx-dev
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./nginx-1.26.3/nginx.conf:/etc/nginx-1.26.3/conf/nginx.conf
      - ./staticfiles:/app/django
    networks:
      - webnet

  spring:
    build: ./spring
    container_name: spring-dev
    ports:
      - "8080:8080"
    networks:
      - webnet

  postgres:
    image: postgres:15
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: roadit_db
      POSTGRES_USER: roadit_user
      POSTGRES_PASSWORD: roadit_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  pgdata: