# Generated by Django 5.1.7 on 2025-04-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
