server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/roadit_db
    username: your_db_user
    password: your_db_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-jwt-secret-key
